export {
  parse,
  SpellDescriptionLexer,
  spellDescriptionParser,
  tokenize,
  visitSpellDescription,
} from "./internal/spell-description";

export type {
  AtVariableNode,
  AuraConditionNode,
  BinaryExpressionNode,
  ClassConditionNode,
  ColorCodeNode,
  ConditionalBranchNode,
  ConditionalNode,
  ConditionalPredicateNode,
  CrossSpellReferenceNode,
  CustomVariableNode,
  DescriptionVariables,
  EffectVariableNode,
  EnchantVariableNode,
  ExpressionBlockNode,
  ExpressionConditionNode,
  ExpressionNode,
  FunctionCallNode,
  GenderNode,
  MiscVariableNode,
  NumberLiteralNode,
  ParenExpressionNode,
  ParsedSpellDescription,
  PlayerConditionNode,
  PlayerContext,
  PlayerVariableNode,
  PluralizationNode,
  ResolutionContext,
  SingleConditionNode,
  SpellData,
  SpellDescriptionNode,
  SpellEffectData,
  SpellKnownConditionNode,
  SpellLevelVariableNode,
  TextNode,
  UnaryExpressionNode,
  VariableNode,
} from "./internal/spell-description";
