// Generated by migration script
// Namespace exports for internal/dbc/

export * from "./FileDataSchema.js";
export * from "./ItemEffectSchema.js";
export * from "./ItemSchema.js";
export * from "./ItemSparseSchema.js";
export * from "./ItemXItemEffectSchema.js";
export * from "./SpellAuraOptionsSchema.js";
export * from "./SpellAuraRestrictionsSchema.js";
export * from "./SpellCastingRequirementsSchema.js";
export * from "./SpellCastTimesSchema.js";
export * from "./SpellCategoriesSchema.js";
export * from "./SpellCategorySchema.js";
export * from "./SpellClassOptionsSchema.js";
export * from "./SpellCooldownsSchema.js";
export * from "./SpellDurationSchema.js";
export * from "./SpellEffectSchema.js";
export * from "./SpellEmpowerSchema.js";
export * from "./SpellEmpowerStageSchema.js";
export * from "./SpellInterruptsSchema.js";
export * from "./SpellMiscSchema.js";
export * from "./SpellNameSchema.js";
export * from "./SpellPowerSchema.js";
export * from "./SpellProcsPerMinuteSchema.js";
export * from "./SpellRadiusSchema.js";
export * from "./SpellRangeSchema.js";
export * from "./SpellSchema.js";
export * from "./SpellShapeshiftSchema.js";
export * from "./SpellTargetRestrictionsSchema.js";
