import * as Schema from "effect/Schema";

const ItemSparseSchema = Schema.Struct({
  AllowableClass: Schema.Number,
  AllowableRace: Schema.Number,
  ArtifactID: Schema.Number,
  BagFamily: Schema.Number,
  Bonding: Schema.Number,
  BuyPrice: Schema.Number,
  ContainerSlots: Schema.Number,
  ContentTuningID: Schema.Number,
  DamageDamageType: Schema.Number,
  Description: Schema.String,
  Display: Schema.String,
  Display1: Schema.String,
  Display2: Schema.String,
  Display3: Schema.String,
  DmgVariance: Schema.Number,
  DurationInInventory: Schema.Number,
  ExpansionID: Schema.Number,
  FactionRelated: Schema.Number,
  Flags: Schema.Array(Schema.Number),
  GemProperties: Schema.Number,
  ID: Schema.Number,
  InstanceBound: Schema.Number,
  InventoryType: Schema.Number,
  ItemDelay: Schema.Number,
  ItemLevel: Schema.Number,
  ItemNameDescriptionID: Schema.Number,
  ItemRange: Schema.Number,
  ItemSet: Schema.Number,
  LanguageID: Schema.Number,
  LimitCategory: Schema.Number,
  LockID: Schema.Number,
  Material: Schema.Number,
  MaxCount: Schema.Number,
  MinFactionID: Schema.Number,
  MinReputation: Schema.Number,
  ModifiedCraftingReagentItemID: Schema.Number,
  OverallQualityID: Schema.Number,
  PageID: Schema.Number,
  PageMaterialID: Schema.Number,
  PlayerLevelToItemLevelCurveID: Schema.Number,
  PriceRandomValue: Schema.Number,
  PriceVariance: Schema.Number,
  QualityModifier: Schema.Number,
  RequiredAbility: Schema.Number,
  RequiredHoliday: Schema.Number,
  RequiredLevel: Schema.Number,
  RequiredPVPMedal: Schema.Number,
  RequiredPVPRank: Schema.Number,
  RequiredSkill: Schema.Number,
  RequiredSkillRank: Schema.Number,
  RequiredTransmogHoliday: Schema.Number,
  SellPrice: Schema.Number,
  SheatheType: Schema.Number,
  SocketMatchEnchantmentId: Schema.Number,
  SocketType: Schema.String,
  SpellWeight: Schema.Number,
  SpellWeightCategory: Schema.Number,
  Stackable: Schema.Number,
  StartQuestID: Schema.Number,
  StatModifierBonusStat: Schema.Array(Schema.Number),
  StatPercentageOfSocket: Schema.Array(Schema.Number),
  StatPercentEditor: Schema.Array(Schema.Number),
  TotemCategoryID: Schema.Number,
  VendorStackCount: Schema.Number,
  ZoneBound: Schema.Array(Schema.Number),
});

type ItemSparseRow = Schema.Schema.Type<typeof ItemSparseSchema>;

export { ItemSparseSchema, type ItemSparseRow };
