packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - better-sqlite3
  - canvas
  - core-js
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
