import * as Schema from "effect/Schema";

import * as Branded from "../Branded.js";

export const SpellEffectRowSchema = Schema.Struct({
  BonusCoefficientFromAP: Schema.NumberFromString,
  Coefficient: Schema.NumberFromString,
  DifficultyID: Schema.NumberFromString,
  Effect: Schema.NumberFromString,
  EffectAmplitude: Schema.NumberFromString,
  EffectAttributes: Schema.NumberFromString,
  EffectAura: Schema.NumberFromString,
  EffectAuraPeriod: Schema.NumberFromString,
  EffectBasePointsF: Schema.NumberFromString,
  EffectBonusCoefficient: Schema.NumberFromString,
  EffectChainAmplitude: Schema.NumberFromString,
  EffectChainTargets: Schema.NumberFromString,
  EffectIndex: Schema.NumberFromString,
  EffectItemType: Schema.NumberFromString,
  EffectMechanic: Schema.NumberFromString,
  EffectMiscValue_0: Schema.NumberFromString,
  EffectMiscValue_1: Schema.NumberFromString,
  EffectPointsPerResource: Schema.NumberFromString,
  EffectPos_facing: Schema.NumberFromString,
  EffectRadiusIndex_0: Schema.NumberFromString,
  EffectRadiusIndex_1: Schema.NumberFromString,
  EffectRealPointsPerLevel: Schema.NumberFromString,
  EffectSpellClassMask_0: Schema.NumberFromString,
  EffectSpellClassMask_1: Schema.NumberFromString,
  EffectSpellClassMask_2: Schema.NumberFromString,
  EffectSpellClassMask_3: Schema.NumberFromString,
  EffectTriggerSpell: Schema.NumberFromString,
  GroupSizeBasePointsCoefficient: Schema.NumberFromString,
  ID: Schema.NumberFromString,
  ImplicitTarget_0: Schema.NumberFromString,
  ImplicitTarget_1: Schema.NumberFromString,
  Node__Field_12_0_0_63534_001: Schema.optional(Schema.NumberFromString),
  PvpMultiplier: Schema.NumberFromString,
  ResourceCoefficient: Schema.NumberFromString,
  ScalingClass: Schema.NumberFromString,
  SpellID: Branded.SpellIDSchema,
  Variance: Schema.NumberFromString,
});

export type SpellEffectRow = Schema.Schema.Type<typeof SpellEffectRowSchema>;
