import * as path from "node:path";

export const AUTOGEN_BANNER =
  "// Auto-generated by scripts/commands/generate-spells.ts. Do not edit manually.\n";

export const OUTPUT_ROOT = path.join(
  process.cwd(),
  "packages",
  "wowlab-core",
  "src",
  "data",
  "spells",
);

export const MANIFEST_PATH = path.join(OUTPUT_ROOT, "generatedSpecLists.ts");

export const TALENTS_PATH = path.join(
  process.cwd(),
  "apps",
  "gamedata-server",
  "data",
  "talents.json",
);
