// Auto-generated by scripts/generateSpellList.ts. Do not edit manually.

import type { SpecSpellList } from "./types";

import {
  classId as classId_deathKnightBlood,
  className as className_deathKnightBlood,
  specId as specId_deathKnightBlood,
  specName as specName_deathKnightBlood,
  spellList as spellList_deathKnightBlood,
} from "./death-knight/blood/spellList";
import {
  classId as classId_deathKnightFrost,
  className as className_deathKnightFrost,
  specId as specId_deathKnightFrost,
  specName as specName_deathKnightFrost,
  spellList as spellList_deathKnightFrost,
} from "./death-knight/frost/spellList";
import {
  classId as classId_deathKnightUnholy,
  className as className_deathKnightUnholy,
  specId as specId_deathKnightUnholy,
  specName as specName_deathKnightUnholy,
  spellList as spellList_deathKnightUnholy,
} from "./death-knight/unholy/spellList";
import {
  classId as classId_demonHunterHavoc,
  className as className_demonHunterHavoc,
  specId as specId_demonHunterHavoc,
  specName as specName_demonHunterHavoc,
  spellList as spellList_demonHunterHavoc,
} from "./demon-hunter/havoc/spellList";
import {
  classId as classId_demonHunterVengeance,
  className as className_demonHunterVengeance,
  specId as specId_demonHunterVengeance,
  specName as specName_demonHunterVengeance,
  spellList as spellList_demonHunterVengeance,
} from "./demon-hunter/vengeance/spellList";
import {
  classId as classId_druidBalance,
  className as className_druidBalance,
  specId as specId_druidBalance,
  specName as specName_druidBalance,
  spellList as spellList_druidBalance,
} from "./druid/balance/spellList";
import {
  classId as classId_druidFeral,
  className as className_druidFeral,
  specId as specId_druidFeral,
  specName as specName_druidFeral,
  spellList as spellList_druidFeral,
} from "./druid/feral/spellList";
import {
  classId as classId_druidGuardian,
  className as className_druidGuardian,
  specId as specId_druidGuardian,
  specName as specName_druidGuardian,
  spellList as spellList_druidGuardian,
} from "./druid/guardian/spellList";
import {
  classId as classId_druidRestoration,
  className as className_druidRestoration,
  specId as specId_druidRestoration,
  specName as specName_druidRestoration,
  spellList as spellList_druidRestoration,
} from "./druid/restoration/spellList";
import {
  classId as classId_evokerAugmentation,
  className as className_evokerAugmentation,
  specId as specId_evokerAugmentation,
  specName as specName_evokerAugmentation,
  spellList as spellList_evokerAugmentation,
} from "./evoker/augmentation/spellList";
import {
  classId as classId_evokerDevastation,
  className as className_evokerDevastation,
  specId as specId_evokerDevastation,
  specName as specName_evokerDevastation,
  spellList as spellList_evokerDevastation,
} from "./evoker/devastation/spellList";
import {
  classId as classId_evokerPreservation,
  className as className_evokerPreservation,
  specId as specId_evokerPreservation,
  specName as specName_evokerPreservation,
  spellList as spellList_evokerPreservation,
} from "./evoker/preservation/spellList";
import {
  classId as classId_hunterBeastMastery,
  className as className_hunterBeastMastery,
  specId as specId_hunterBeastMastery,
  specName as specName_hunterBeastMastery,
  spellList as spellList_hunterBeastMastery,
} from "./hunter/beast-mastery/spellList";
import {
  classId as classId_hunterMarksmanship,
  className as className_hunterMarksmanship,
  specId as specId_hunterMarksmanship,
  specName as specName_hunterMarksmanship,
  spellList as spellList_hunterMarksmanship,
} from "./hunter/marksmanship/spellList";
import {
  classId as classId_hunterSurvival,
  className as className_hunterSurvival,
  specId as specId_hunterSurvival,
  specName as specName_hunterSurvival,
  spellList as spellList_hunterSurvival,
} from "./hunter/survival/spellList";
import {
  classId as classId_mageArcane,
  className as className_mageArcane,
  specId as specId_mageArcane,
  specName as specName_mageArcane,
  spellList as spellList_mageArcane,
} from "./mage/arcane/spellList";
import {
  classId as classId_mageFire,
  className as className_mageFire,
  specId as specId_mageFire,
  specName as specName_mageFire,
  spellList as spellList_mageFire,
} from "./mage/fire/spellList";
import {
  classId as classId_mageFrost,
  className as className_mageFrost,
  specId as specId_mageFrost,
  specName as specName_mageFrost,
  spellList as spellList_mageFrost,
} from "./mage/frost/spellList";
import {
  classId as classId_monkBrewmaster,
  className as className_monkBrewmaster,
  specId as specId_monkBrewmaster,
  specName as specName_monkBrewmaster,
  spellList as spellList_monkBrewmaster,
} from "./monk/brewmaster/spellList";
import {
  classId as classId_monkMistweaver,
  className as className_monkMistweaver,
  specId as specId_monkMistweaver,
  specName as specName_monkMistweaver,
  spellList as spellList_monkMistweaver,
} from "./monk/mistweaver/spellList";
import {
  classId as classId_monkWindwalker,
  className as className_monkWindwalker,
  specId as specId_monkWindwalker,
  specName as specName_monkWindwalker,
  spellList as spellList_monkWindwalker,
} from "./monk/windwalker/spellList";
import {
  classId as classId_paladinHoly,
  className as className_paladinHoly,
  specId as specId_paladinHoly,
  specName as specName_paladinHoly,
  spellList as spellList_paladinHoly,
} from "./paladin/holy/spellList";
import {
  classId as classId_paladinProtection,
  className as className_paladinProtection,
  specId as specId_paladinProtection,
  specName as specName_paladinProtection,
  spellList as spellList_paladinProtection,
} from "./paladin/protection/spellList";
import {
  classId as classId_paladinRetribution,
  className as className_paladinRetribution,
  specId as specId_paladinRetribution,
  specName as specName_paladinRetribution,
  spellList as spellList_paladinRetribution,
} from "./paladin/retribution/spellList";
import {
  classId as classId_priestDiscipline,
  className as className_priestDiscipline,
  specId as specId_priestDiscipline,
  specName as specName_priestDiscipline,
  spellList as spellList_priestDiscipline,
} from "./priest/discipline/spellList";
import {
  classId as classId_priestHoly,
  className as className_priestHoly,
  specId as specId_priestHoly,
  specName as specName_priestHoly,
  spellList as spellList_priestHoly,
} from "./priest/holy/spellList";
import {
  classId as classId_priestShadow,
  className as className_priestShadow,
  specId as specId_priestShadow,
  specName as specName_priestShadow,
  spellList as spellList_priestShadow,
} from "./priest/shadow/spellList";
import {
  classId as classId_rogueAssassination,
  className as className_rogueAssassination,
  specId as specId_rogueAssassination,
  specName as specName_rogueAssassination,
  spellList as spellList_rogueAssassination,
} from "./rogue/assassination/spellList";
import {
  classId as classId_rogueOutlaw,
  className as className_rogueOutlaw,
  specId as specId_rogueOutlaw,
  specName as specName_rogueOutlaw,
  spellList as spellList_rogueOutlaw,
} from "./rogue/outlaw/spellList";
import {
  classId as classId_rogueSubtlety,
  className as className_rogueSubtlety,
  specId as specId_rogueSubtlety,
  specName as specName_rogueSubtlety,
  spellList as spellList_rogueSubtlety,
} from "./rogue/subtlety/spellList";
import {
  classId as classId_shamanElemental,
  className as className_shamanElemental,
  specId as specId_shamanElemental,
  specName as specName_shamanElemental,
  spellList as spellList_shamanElemental,
} from "./shaman/elemental/spellList";
import {
  classId as classId_shamanEnhancement,
  className as className_shamanEnhancement,
  specId as specId_shamanEnhancement,
  specName as specName_shamanEnhancement,
  spellList as spellList_shamanEnhancement,
} from "./shaman/enhancement/spellList";
import {
  classId as classId_shamanRestoration,
  className as className_shamanRestoration,
  specId as specId_shamanRestoration,
  specName as specName_shamanRestoration,
  spellList as spellList_shamanRestoration,
} from "./shaman/restoration/spellList";
import {
  classId as classId_warlockAffliction,
  className as className_warlockAffliction,
  specId as specId_warlockAffliction,
  specName as specName_warlockAffliction,
  spellList as spellList_warlockAffliction,
} from "./warlock/affliction/spellList";
import {
  classId as classId_warlockDemonology,
  className as className_warlockDemonology,
  specId as specId_warlockDemonology,
  specName as specName_warlockDemonology,
  spellList as spellList_warlockDemonology,
} from "./warlock/demonology/spellList";
import {
  classId as classId_warlockDestruction,
  className as className_warlockDestruction,
  specId as specId_warlockDestruction,
  specName as specName_warlockDestruction,
  spellList as spellList_warlockDestruction,
} from "./warlock/destruction/spellList";
import {
  classId as classId_warriorArms,
  className as className_warriorArms,
  specId as specId_warriorArms,
  specName as specName_warriorArms,
  spellList as spellList_warriorArms,
} from "./warrior/arms/spellList";
import {
  classId as classId_warriorFury,
  className as className_warriorFury,
  specId as specId_warriorFury,
  specName as specName_warriorFury,
  spellList as spellList_warriorFury,
} from "./warrior/fury/spellList";
import {
  classId as classId_warriorProtection,
  className as className_warriorProtection,
  specId as specId_warriorProtection,
  specName as specName_warriorProtection,
  spellList as spellList_warriorProtection,
} from "./warrior/protection/spellList";

export const SPEC_SPELL_LISTS: readonly SpecSpellList[] = [
  {
    classId: classId_druidBalance,
    className: className_druidBalance,
    specId: specId_druidBalance,
    specName: specName_druidBalance,
    spellList: spellList_druidBalance,
  },
  {
    classId: classId_druidFeral,
    className: className_druidFeral,
    specId: specId_druidFeral,
    specName: specName_druidFeral,
    spellList: spellList_druidFeral,
  },
  {
    classId: classId_druidGuardian,
    className: className_druidGuardian,
    specId: specId_druidGuardian,
    specName: specName_druidGuardian,
    spellList: spellList_druidGuardian,
  },
  {
    classId: classId_druidRestoration,
    className: className_druidRestoration,
    specId: specId_druidRestoration,
    specName: specName_druidRestoration,
    spellList: spellList_druidRestoration,
  },
  {
    classId: classId_evokerDevastation,
    className: className_evokerDevastation,
    specId: specId_evokerDevastation,
    specName: specName_evokerDevastation,
    spellList: spellList_evokerDevastation,
  },
  {
    classId: classId_evokerPreservation,
    className: className_evokerPreservation,
    specId: specId_evokerPreservation,
    specName: specName_evokerPreservation,
    spellList: spellList_evokerPreservation,
  },
  {
    classId: classId_evokerAugmentation,
    className: className_evokerAugmentation,
    specId: specId_evokerAugmentation,
    specName: specName_evokerAugmentation,
    spellList: spellList_evokerAugmentation,
  },
  {
    classId: classId_priestDiscipline,
    className: className_priestDiscipline,
    specId: specId_priestDiscipline,
    specName: specName_priestDiscipline,
    spellList: spellList_priestDiscipline,
  },
  {
    classId: classId_priestHoly,
    className: className_priestHoly,
    specId: specId_priestHoly,
    specName: specName_priestHoly,
    spellList: spellList_priestHoly,
  },
  {
    classId: classId_priestShadow,
    className: className_priestShadow,
    specId: specId_priestShadow,
    specName: specName_priestShadow,
    spellList: spellList_priestShadow,
  },
  {
    classId: classId_deathKnightBlood,
    className: className_deathKnightBlood,
    specId: specId_deathKnightBlood,
    specName: specName_deathKnightBlood,
    spellList: spellList_deathKnightBlood,
  },
  {
    classId: classId_deathKnightFrost,
    className: className_deathKnightFrost,
    specId: specId_deathKnightFrost,
    specName: specName_deathKnightFrost,
    spellList: spellList_deathKnightFrost,
  },
  {
    classId: classId_deathKnightUnholy,
    className: className_deathKnightUnholy,
    specId: specId_deathKnightUnholy,
    specName: specName_deathKnightUnholy,
    spellList: spellList_deathKnightUnholy,
  },
  {
    classId: classId_hunterBeastMastery,
    className: className_hunterBeastMastery,
    specId: specId_hunterBeastMastery,
    specName: specName_hunterBeastMastery,
    spellList: spellList_hunterBeastMastery,
  },
  {
    classId: classId_hunterMarksmanship,
    className: className_hunterMarksmanship,
    specId: specId_hunterMarksmanship,
    specName: specName_hunterMarksmanship,
    spellList: spellList_hunterMarksmanship,
  },
  {
    classId: classId_hunterSurvival,
    className: className_hunterSurvival,
    specId: specId_hunterSurvival,
    specName: specName_hunterSurvival,
    spellList: spellList_hunterSurvival,
  },
  {
    classId: classId_rogueAssassination,
    className: className_rogueAssassination,
    specId: specId_rogueAssassination,
    specName: specName_rogueAssassination,
    spellList: spellList_rogueAssassination,
  },
  {
    classId: classId_rogueOutlaw,
    className: className_rogueOutlaw,
    specId: specId_rogueOutlaw,
    specName: specName_rogueOutlaw,
    spellList: spellList_rogueOutlaw,
  },
  {
    classId: classId_rogueSubtlety,
    className: className_rogueSubtlety,
    specId: specId_rogueSubtlety,
    specName: specName_rogueSubtlety,
    spellList: spellList_rogueSubtlety,
  },
  {
    classId: classId_shamanElemental,
    className: className_shamanElemental,
    specId: specId_shamanElemental,
    specName: specName_shamanElemental,
    spellList: spellList_shamanElemental,
  },
  {
    classId: classId_shamanEnhancement,
    className: className_shamanEnhancement,
    specId: specId_shamanEnhancement,
    specName: specName_shamanEnhancement,
    spellList: spellList_shamanEnhancement,
  },
  {
    classId: classId_shamanRestoration,
    className: className_shamanRestoration,
    specId: specId_shamanRestoration,
    specName: specName_shamanRestoration,
    spellList: spellList_shamanRestoration,
  },
  {
    classId: classId_paladinHoly,
    className: className_paladinHoly,
    specId: specId_paladinHoly,
    specName: specName_paladinHoly,
    spellList: spellList_paladinHoly,
  },
  {
    classId: classId_paladinProtection,
    className: className_paladinProtection,
    specId: specId_paladinProtection,
    specName: specName_paladinProtection,
    spellList: spellList_paladinProtection,
  },
  {
    classId: classId_paladinRetribution,
    className: className_paladinRetribution,
    specId: specId_paladinRetribution,
    specName: specName_paladinRetribution,
    spellList: spellList_paladinRetribution,
  },
  {
    classId: classId_mageArcane,
    className: className_mageArcane,
    specId: specId_mageArcane,
    specName: specName_mageArcane,
    spellList: spellList_mageArcane,
  },
  {
    classId: classId_mageFire,
    className: className_mageFire,
    specId: specId_mageFire,
    specName: specName_mageFire,
    spellList: spellList_mageFire,
  },
  {
    classId: classId_mageFrost,
    className: className_mageFrost,
    specId: specId_mageFrost,
    specName: specName_mageFrost,
    spellList: spellList_mageFrost,
  },
  {
    classId: classId_warriorArms,
    className: className_warriorArms,
    specId: specId_warriorArms,
    specName: specName_warriorArms,
    spellList: spellList_warriorArms,
  },
  {
    classId: classId_warriorFury,
    className: className_warriorFury,
    specId: specId_warriorFury,
    specName: specName_warriorFury,
    spellList: spellList_warriorFury,
  },
  {
    classId: classId_warriorProtection,
    className: className_warriorProtection,
    specId: specId_warriorProtection,
    specName: specName_warriorProtection,
    spellList: spellList_warriorProtection,
  },
  {
    classId: classId_warlockAffliction,
    className: className_warlockAffliction,
    specId: specId_warlockAffliction,
    specName: specName_warlockAffliction,
    spellList: spellList_warlockAffliction,
  },
  {
    classId: classId_warlockDemonology,
    className: className_warlockDemonology,
    specId: specId_warlockDemonology,
    specName: specName_warlockDemonology,
    spellList: spellList_warlockDemonology,
  },
  {
    classId: classId_warlockDestruction,
    className: className_warlockDestruction,
    specId: specId_warlockDestruction,
    specName: specName_warlockDestruction,
    spellList: spellList_warlockDestruction,
  },
  {
    classId: classId_monkBrewmaster,
    className: className_monkBrewmaster,
    specId: specId_monkBrewmaster,
    specName: specName_monkBrewmaster,
    spellList: spellList_monkBrewmaster,
  },
  {
    classId: classId_monkWindwalker,
    className: className_monkWindwalker,
    specId: specId_monkWindwalker,
    specName: specName_monkWindwalker,
    spellList: spellList_monkWindwalker,
  },
  {
    classId: classId_monkMistweaver,
    className: className_monkMistweaver,
    specId: specId_monkMistweaver,
    specName: specName_monkMistweaver,
    spellList: spellList_monkMistweaver,
  },
  {
    classId: classId_demonHunterHavoc,
    className: className_demonHunterHavoc,
    specId: specId_demonHunterHavoc,
    specName: specName_demonHunterHavoc,
    spellList: spellList_demonHunterHavoc,
  },
  {
    classId: classId_demonHunterVengeance,
    className: className_demonHunterVengeance,
    specId: specId_demonHunterVengeance,
    specName: specName_demonHunterVengeance,
    spellList: spellList_demonHunterVengeance,
  },
] as const;
