import * as Entities from "@wowlab/core/Entities";
import * as Schemas from "@wowlab/core/Schemas";
import { Map } from "immutable";

export const createPlayerUnit = (): Entities.Unit.Unit => ({
  auras: { all: Map<Schemas.Branded.SpellID, Entities.Aura.Aura>(), meta: {} },
  castingSpellId: null,
  castRemaining: 0,
  castTarget: Schemas.Branded.UnitID("enemy"),
  health: Entities.Power.Power.create({ current: 25000, max: 25000 }),
  id: Schemas.Branded.UnitID("player"),
  isCasting: false,
  isPlayer: true,
  name: "Player",
  paperDoll: Entities.PaperDoll.PaperDoll.create({
    armor: 0,
    avoidance: 0,
    class: "Mage",
    critRating: 0,
    hasteRating: 0,
    level: 80,
    mainStat: 0,
    masteryPercent: 0,
    stamina: 0,
    versatilityRating: 0,
  }),
  position: { x: 0, y: 0, z: 0 },
  power: Map<Schemas.Enums.PowerType, Entities.Power.Power>([
    ["mana", Entities.Power.Power.create({ current: 15000, max: 15000 })],
    ["rage", Entities.Power.Power.create({ current: 0, max: 100 })],
    ["focus", Entities.Power.Power.create({ current: 100, max: 100 })],
    ["energy", Entities.Power.Power.create({ current: 100, max: 100 })],
    ["comboPoints", Entities.Power.Power.create({ current: 0, max: 5 })],
    ["runes", Entities.Power.Power.create({ current: 6, max: 6 })],
    ["runicPower", Entities.Power.Power.create({ current: 0, max: 100 })],
    ["soulShards", Entities.Power.Power.create({ current: 3, max: 5 })],
    ["lunarPower", Entities.Power.Power.create({ current: 0, max: 100 })],
    ["holyPower", Entities.Power.Power.create({ current: 0, max: 5 })],
    ["alternativePower", Entities.Power.Power.create({ current: 0, max: 100 })],
    ["maelstrom", Entities.Power.Power.create({ current: 0, max: 100 })],
    ["chi", Entities.Power.Power.create({ current: 0, max: 6 })],
    ["insanity", Entities.Power.Power.create({ current: 0, max: 100 })],
    ["burningEmbers", Entities.Power.Power.create({ current: 0, max: 0 })],
    ["demonicFury", Entities.Power.Power.create({ current: 0, max: 0 })],
    ["arcaneCharges", Entities.Power.Power.create({ current: 0, max: 4 })],
    ["fury", Entities.Power.Power.create({ current: 0, max: 100 })],
    ["pain", Entities.Power.Power.create({ current: 0, max: 100 })],
  ]),
  profiles: ["player-base", "class-mage", "spec-mage-fire"],
  spells: {
    all: Map(),
    meta: { cooldownCategories: Map() },
  },
});

export const createEnemyUnit = (): Entities.Unit.Unit => ({
  auras: { all: Map<Schemas.Branded.SpellID, Entities.Aura.Aura>(), meta: {} },
  castingSpellId: null,
  castRemaining: 0,
  castTarget: null,
  health: Entities.Power.Power.create({ current: 100000, max: 100000 }),
  id: Schemas.Branded.UnitID("enemy"),
  isCasting: false,
  isPlayer: false,
  name: "Target Dummy",
  paperDoll: Entities.PaperDoll.PaperDoll.create({
    armor: 0,
    avoidance: 0,
    class: "Warrior",
    critRating: 0,
    hasteRating: 0,
    level: 83,
    mainStat: 0,
    masteryPercent: 0,
    stamina: 0,
    versatilityRating: 0,
  }),
  position: { x: 10, y: 0, z: 0 },
  power: Map(),
  profiles: ["npc-base"],
  spells: {
    all: Map(),
    meta: { cooldownCategories: Map() },
  },
});
