import * as Schema from "effect/Schema";

export const ChrClassesRowSchema = Schema.Struct({
  Name_lang: Schema.NullOr(Schema.String),
  Filename: Schema.NullOr(Schema.String),
  Name_male_lang: Schema.NullOr(Schema.String),
  Name_female_lang: Schema.NullOr(Schema.String),
  PetNameToken: Schema.NullOr(Schema.String),
  Description_lang: Schema.NullOr(Schema.String),
  RoleInfoString_lang: Schema.NullOr(Schema.String),
  DisabledString_lang: Schema.NullOr(Schema.String),
  Hyphenated_name_male_lang: Schema.NullOr(Schema.String),
  Hyphenated_name_female_lang: Schema.NullOr(Schema.String),
  CreateScreenFileDataID: Schema.NumberFromString,
  SelectScreenFileDataID: Schema.NumberFromString,
  IconFileDataID: Schema.NumberFromString,
  LowResScreenFileDataID: Schema.NumberFromString,
  Flags: Schema.NumberFromString,
  StartingLevel: Schema.NumberFromString,
  SpellTextureBlobFileDataID: Schema.NumberFromString,
  ArmorTypeMask: Schema.NumberFromString,
  Field_9_0_1_34490_018: Schema.NumberFromString,
  MaleCharacterCreationVisualFallback: Schema.NumberFromString,
  MaleCharacterCreationIdleVisualFallback: Schema.NumberFromString,
  FemaleCharacterCreationVisualFallback: Schema.NumberFromString,
  FemaleCharacterCreationIdleVisualFallback: Schema.NumberFromString,
  CharacterCreationIdleGroundVisualFallback: Schema.NumberFromString,
  CharacterCreationGroundVisualFallback: Schema.NumberFromString,
  AlteredFormCharacterCreationIdleVisualFallback: Schema.NumberFromString,
  CharacterCreationAnimLoopWaitTimeMsFallback: Schema.NumberFromString,
  CinematicSequenceID: Schema.NumberFromString,
  DefaultSpec: Schema.NumberFromString,
  ID: Schema.NumberFromString,
  HasStrengthAttackBonus: Schema.NumberFromString,
  PrimaryStatPriority: Schema.NumberFromString,
  DisplayPower: Schema.NumberFromString,
  RangedAttackPowerPerAgility: Schema.NumberFromString,
  AttackPowerPerAgility: Schema.NumberFromString,
  AttackPowerPerStrength: Schema.NumberFromString,
  SpellClassSet: Schema.NumberFromString,
  ClassColorR: Schema.NumberFromString,
  ClassColorG: Schema.NumberFromString,
  ClassColorB: Schema.NumberFromString,
  RolesMask: Schema.NumberFromString,
  DamageBonusStat: Schema.NumberFromString,
  HasRelicSlot: Schema.NumberFromString,
});

export type ChrClassesRow = Schema.Schema.Type<typeof ChrClassesRowSchema>;
