import * as Schema from "effect/Schema";

export const ChrRacesRowSchema = Schema.Struct({
  ID: Schema.NumberFromString,
  ClientPrefix: Schema.NullOr(Schema.String),
  ClientFileString: Schema.NullOr(Schema.String),
  Name_lang: Schema.NullOr(Schema.String),
  Name_female_lang: Schema.NullOr(Schema.String),
  Name_lowercase_lang: Schema.NullOr(Schema.String),
  Name_female_lowercase_lang: Schema.NullOr(Schema.String),
  Lore_name_lang: Schema.NullOr(Schema.String),
  Lore_name_female_lang: Schema.NullOr(Schema.String),
  Lore_name_lower_lang: Schema.NullOr(Schema.String),
  Lore_name_lower_female_lang: Schema.NullOr(Schema.String),
  LoreDescription_lang: Schema.NullOr(Schema.String),
  Short_name_lang: Schema.NullOr(Schema.String),
  Short_name_female_lang: Schema.NullOr(Schema.String),
  Short_name_lower_lang: Schema.NullOr(Schema.String),
  Short_name_lower_female_lang: Schema.NullOr(Schema.String),
  Flags: Schema.NumberFromString,
  FactionID: Schema.NumberFromString,
  CinematicSequenceID: Schema.NumberFromString,
  ResSicknessSpellID: Schema.NumberFromString,
  SplashSoundID: Schema.NumberFromString,
  CreateScreenFileDataID: Schema.NumberFromString,
  SelectScreenFileDataID: Schema.NumberFromString,
  LowResScreenFileDataID: Schema.NumberFromString,
  AlteredFormStartVisualKitID_0: Schema.NumberFromString,
  AlteredFormStartVisualKitID_1: Schema.NumberFromString,
  AlteredFormStartVisualKitID_2: Schema.NumberFromString,
  AlteredFormFinishVisualKitID_0: Schema.NumberFromString,
  AlteredFormFinishVisualKitID_1: Schema.NumberFromString,
  AlteredFormFinishVisualKitID_2: Schema.NumberFromString,
  HeritageArmorAchievementID: Schema.NumberFromString,
  StartingLevel: Schema.NumberFromString,
  UiDisplayOrder: Schema.NumberFromString,
  PlayableRaceBit: Schema.NumberFromString,
  TransmogrifyDisabledSlotMask: Schema.NumberFromString,
  AlteredFormCustomizeOffsetFallback_0: Schema.NumberFromString,
  AlteredFormCustomizeOffsetFallback_1: Schema.NumberFromString,
  AlteredFormCustomizeOffsetFallback_2: Schema.NumberFromString,
  AlteredFormCustomizeRotationFallback: Schema.NumberFromString,
  Field_9_1_0_38312_030_0: Schema.NumberFromString,
  Field_9_1_0_38312_030_1: Schema.NumberFromString,
  Field_9_1_0_38312_030_2: Schema.NumberFromString,
  Field_9_1_0_38312_031_0: Schema.NumberFromString,
  Field_9_1_0_38312_031_1: Schema.NumberFromString,
  Field_9_1_0_38312_031_2: Schema.NumberFromString,
  BaseLanguage: Schema.NumberFromString,
  CreatureType: Schema.NumberFromString,
  Alliance: Schema.NumberFromString,
  Race_related: Schema.NumberFromString,
  UnalteredVisualRaceID: Schema.NumberFromString,
  DefaultClassID: Schema.NumberFromString,
  NeutralRaceID: Schema.NumberFromString,
  MaleModelFallbackRaceID: Schema.NumberFromString,
  MaleModelFallbackSex: Schema.NumberFromString,
  FemaleModelFallbackRaceID: Schema.NumberFromString,
  FemaleModelFallbackSex: Schema.NumberFromString,
  MaleTextureFallbackRaceID: Schema.NumberFromString,
  MaleTextureFallbackSex: Schema.NumberFromString,
  FemaleTextureFallbackRaceID: Schema.NumberFromString,
  FemaleTextureFallbackSex: Schema.NumberFromString,
  HelmetAnimScalingRaceID: Schema.NumberFromString,
  UnalteredVisualCustomizationRaceID: Schema.NumberFromString,
});

export type ChrRacesRow = Schema.Schema.Type<typeof ChrRacesRowSchema>;
