import * as Schema from "effect/Schema";

/**
 * Auto-generated from World of Warcraft 11.2.5.63906
 * Source: https://github.com/Gethe/wow-ui-source/tree/7dd1c12d542cf2e0c46ce9282886287f3fd0a2c7
 */

/* eslint-disable perfectionist/sort-enums */
export enum AccountTransType {
  ProxyForwarder = 0,
  Purchase = 1,
  Distribution = 2,
  Battlepet = 3,
  Achievements = 4,
  Criteria = 5,
  Mounts = 6,
  Characters = 7,
  Purchases = 8,
  ArchivedPurchases = 9,
  Distributions = 10,
  CurrencyCaps = 11,
  QuestLog = 12,
  CriteriaNotif = 13,
  Settings = 14,
  FixedLicense = 15,
  AddLicense = 16,
  ItemCollections = 17,
  AuctionableToken = 18,
  ConsumableToken = 19,
  VasTransaction = 20,
  Productitem = 21,
  TrialBoostHistory = 22,
  TrialBoostHistories = 23,
  QuestCriteria = 24,
  BattlenetAccount = 25,
  AccountCurrencies = 26,
  RafRecruiterAcceptances = 27,
  RafFriendMonth = 28,
  RafReward = 29,
  DynamicCriteria = 30,
  RafActivity = 31,
  CreateOrderInfo = 32,
  ProxyHonorInitialConversion = 33,
  ProxyCreateAccountHonor = 34,
  ProxyValidateAccountHonor = 35,
  ProxyGmSetHonor = 36,
  ProxyGenerateBpayID = 37,
  AccountNotifications = 38,
  PerkItemHold = 39,
  PerkPendingRewards = 40,
  PerkPastRewards = 41,
  PerkTransaction = 42,
  OutstandingRpc = 43,
  LoadWowlabs = 44,
  UpgradeAccount = 45,
  GetOrderStatusByPurchaseID = 46,
  Items = 47,
  BankTab = 48,
  Factions = 49,
  BitVectors = 50,
  CombinedQuestLog = 51,
  PlayerDataElements = 52,
  CharacterDataMerge = 53,
  AccountStore = 54,
  WarbandGroups = 55,
  Mapping = 56,
  CharacterItems = 57,
  CurrencyTransferLog = 58,
  LgVendorPurchase = 59,
  SaveWarbandGroups = 60,
  Profile = 61,
  WarbandSceneCollection = 62,
  EventRecords = 63,
}

export const AccountTransTypeSchema = Schema.Enums(AccountTransType);
