import * as Schema from "effect/Schema";

/**
 * Auto-generated from World of Warcraft 11.2.5.63906
 * Source: https://github.com/Gethe/wow-ui-source/tree/7dd1c12d542cf2e0c46ce9282886287f3fd0a2c7
 */

/* eslint-disable perfectionist/sort-enums */
export enum BonusStatIndex {
  Mana = 0,
  Health = 1,
  Endurance = 2,
  Agility = 3,
  Strength = 4,
  Intellect = 5,
  Spirit = 6,
  Stamina = 7,
  Energy = 8,
  Rage = 9,
  Focus = 10,
  WeaponSkillRatingObsolete = 11,
  DefenseSkillRating = 12,
  DodgeRating = 13,
  ParryRating = 14,
  BlockRating = 15,
  HitMeleeRating = 16,
  HitRangedRating = 17,
  HitSpellRating = 18,
  CritMeleeRating = 19,
  CritRangedRating = 20,
  CritSpellRating = 21,
  Corruption = 22,
  CorruptionResistance = 23,
  ModifiedCraftingStat_1 = 24,
  ModifiedCraftingStat_2 = 25,
  CritTakenRangedRatingObsolete = 26,
  CritTakenSpellRatingObsolete = 27,
  HasteMeleeRatingObsolete = 28,
  HasteRangedRatingObsolete = 29,
  HasteSpellRatingObsolete = 30,
  HitRating = 31,
  CritRating = 32,
  HitTakenRatingObsolete = 33,
  CritTakenRatingObsolete = 34,
  ResilienceRating = 35,
  HasteRating = 36,
  ExpertiseRating = 37,
  AttackPower = 38,
  RangedAttackPower = 39,
  Versatility = 40,
  SpellHealingDone = 41,
  SpellDamageDone = 42,
  ManaRegenerationObsolete = 43,
  Unused = 44,
  SpellPower = 45,
  HealthRegen = 46,
  SpellPenetration = 47,
  BlockValueObsolete = 48,
  MasteryRating = 49,
  ExtraArmor = 50,
  FireResistance = 51,
  FrostResistance = 52,
  HolyResistance = 53,
  ShadowResistance = 54,
  NatureResistance = 55,
  ArcaneResistance = 56,
  PvPPower = 57,
  CombatRatingUnused_0 = 58,
  CombatRatingUnused_2 = 59,
  CombatRatingUnused_3 = 60,
  CombatRatingSpeed = 61,
  CombatRatingLifesteal = 62,
  CombatRatingAvoidance = 63,
  CombatRatingSturdiness = 64,
  CombatRatingUnused_7 = 65,
  CombatRatingUnused_27 = 66,
  CombatRatingUnused_9 = 67,
  CombatRatingUnused_10 = 68,
  CombatRatingUnused_11 = 69,
  CombatRatingUnused_12 = 70,
  AgilityOrStrengthOrIntellect = 71,
  AgilityOrStrength = 72,
  AgilityOrIntellect = 73,
  StrengthOrIntellect = 74,
  ProfessionInspiration = 75,
  ProfessionResourcefulness = 76,
  ProfessionFinesse = 77,
  ProfessionDeftness = 78,
  ProfessionPerception = 79,
  ProfessionCraftingSpeed = 80,
  ProfessionMulticraft = 81,
  ProfessionIngenuity = 82,
}

export const BonusStatIndexSchema = Schema.Enums(BonusStatIndex);
