import * as Schema from "effect/Schema";

/**
 * Auto-generated from World of Warcraft 11.2.5.63906
 * Source: https://github.com/Gethe/wow-ui-source/tree/7dd1c12d542cf2e0c46ce9282886287f3fd0a2c7
 */

/* eslint-disable perfectionist/sort-enums */
export enum CurrencySource {
  ConvertOldItem = 0,
  ConvertOldPvPCurrency = 1,
  ItemRefund = 2,
  QuestReward = 3,
  Cheat = 4,
  Vendor = 5,
  PvPKillCredit = 6,
  PvPMetaCredit = 7,
  PvPScriptedAward = 8,
  Loot = 9,
  UpdatingVersion = 10,
  LFGReward = 11,
  Trade = 12,
  Spell = 13,
  ItemDeletion = 14,
  RatedBattleground = 15,
  RandomBattleground = 16,
  Arena = 17,
  ExceededMaxQty = 18,
  PvPCompletionBonus = 19,
  Script = 20,
  GuildBankWithdrawal = 21,
  Pushloot = 22,
  GarrisonBuilding = 23,
  PvPDrop = 24,
  GarrisonFollowerActivation = 25,
  GarrisonBuildingRefund = 26,
  GarrisonMissionReward = 27,
  GarrisonResourceOverTime = 28,
  QuestRewardIgnoreCapsDeprecated = 29,
  GarrisonTalent = 30,
  GarrisonWorldQuestBonus = 31,
  PvPHonorReward = 32,
  BonusRoll = 33,
  AzeriteRespec = 34,
  WorldQuestReward = 35,
  WorldQuestRewardIgnoreCapsDeprecated = 36,
  FactionConversion = 37,
  DailyQuestReward = 38,
  DailyQuestWarModeReward = 39,
  WeeklyQuestReward = 40,
  WeeklyQuestWarModeReward = 41,
  AccountCopy = 42,
  WeeklyRewardChest = 43,
  GarrisonTalentTreeReset = 44,
  DailyReset = 45,
  AddConduitToCollection = 46,
  Barbershop = 47,
  ConvertItemsToCurrencyValue = 48,
  PvPTeamContribution = 49,
  Transmogrify = 50,
  AuctionDeposit = 51,
  PlayerTrait = 52,
  PhBuffer_53 = 53,
  PhBuffer_54 = 54,
  RenownRepGain = 55,
  CraftingOrder = 56,
  CatalystBalancing = 57,
  CatalystCraft = 58,
  ProfessionInitialAward = 59,
  PlayerTraitRefund = 60,
  AccountHwmUpdate = 61,
  ConvertItemsToCurrencyAndReputation = 62,
  PhBuffer_63 = 63,
  SpellSkipLinkedCurrency = 64,
  AccountTransfer = 65,
  RenownRepGainInitialVisibility = 66,
}

export const CurrencySourceSchema = Schema.Enums(CurrencySource);
