import * as Schema from "effect/Schema";

/**
 * Auto-generated from World of Warcraft 11.2.5.63906
 * Source: https://github.com/Gethe/wow-ui-source/tree/7dd1c12d542cf2e0c46ce9282886287f3fd0a2c7
 */

/* eslint-disable perfectionist/sort-enums */
export enum Cursormode {
  NoCursor = 0,
  PointCursor = 1,
  CastCursor = 2,
  BuyCursor = 3,
  AttackCursor = 4,
  InteractCursor = 5,
  SpeakCursor = 6,
  InspectCursor = 7,
  PickupCursor = 8,
  TaxiCursor = 9,
  TrainerCursor = 10,
  MineCursor = 11,
  SkinCursor = 12,
  GatherCursor = 13,
  LockCursor = 14,
  MailCursor = 15,
  LootAllCursor = 16,
  RepairCursor = 17,
  RepairnpcCursor = 18,
  ItemCursor = 19,
  SkinHordeCursor = 20,
  SkinAllianceCursor = 21,
  InnkeeperCursor = 22,
  CampaignQuestCursor = 23,
  CampaignQuestTurninCursor = 24,
  QuestCursor = 25,
  QuestRepeatableCursor = 26,
  QuestTurninCursor = 27,
  QuestLegendaryCursor = 28,
  QuestLegendaryTurninCursor = 29,
  QuestImportantCursor = 30,
  QuestImportantTurninCursor = 31,
  QuestMetaCursor = 32,
  QuestMetaTurninCursor = 33,
  QuestRecurringCursor = 34,
  QuestRecurringTurninCursor = 35,
  VehicleCursor = 36,
  MapPinCursor = 37,
  PingCursor = 38,
  EnchantCursor = 39,
  StablemasterCursor = 40,
  UIMoveCursor = 41,
  UIResizeCursor = 42,
  PointErrorCursor = 43,
  CastErrorCursor = 44,
  BuyErrorCursor = 45,
  AttackErrorCursor = 46,
  InteractErrorCursor = 47,
  SpeakErrorCursor = 48,
  InspectErrorCursor = 49,
  PickupErrorCursor = 50,
  TaxiErrorCursor = 51,
  TrainerErrorCursor = 52,
  MineErrorCursor = 53,
  SkinErrorCursor = 54,
  GatherErrorCursor = 55,
  LockErrorCursor = 56,
  MailErrorCursor = 57,
  LootAllErrorCursor = 58,
  RepairErrorCursor = 59,
  RepairnpcErrorCursor = 60,
  ItemErrorCursor = 61,
  SkinHordeErrorCursor = 62,
  SkinAllianceErrorCursor = 63,
  InnkeeperErrorCursor = 64,
  CampaignQuestErrorCursor = 65,
  CampaignQuestTurninErrorCursor = 66,
  QuestErrorCursor = 67,
  QuestRepeatableErrorCursor = 68,
  QuestTurninErrorCursor = 69,
  QuestLegendaryErrorCursor = 70,
  QuestLegendaryTurninErrorCursor = 71,
  QuestImportantErrorCursor = 72,
  QuestImportantTurninErrorCursor = 73,
  QuestMetaErrorCursor = 74,
  QuestMetaTurninErrorCursor = 75,
  QuestRecurringErrorCursor = 76,
  QuestRecurringTurninErrorCursor = 77,
  VehicleErrorCursor = 78,
  MapPinErrorCursor = 79,
  PingErrorCursor = 80,
  EnchantErrorCursor = 81,
  StablemasterErrorCursor = 82,
  CustomCursor = 83,
}

export const CursormodeSchema = Schema.Enums(Cursormode);
