import * as Schema from "effect/Schema";

/**
 * Auto-generated from World of Warcraft 11.2.5.63906
 * Source: https://github.com/Gethe/wow-ui-source/tree/7dd1c12d542cf2e0c46ce9282886287f3fd0a2c7
 */

/* eslint-disable perfectionist/sort-enums */
export enum GossipNpcOption {
  None = 0,
  Vendor = 1,
  Taxinode = 2,
  Trainer = 3,
  SpiritHealer = 4,
  Binder = 5,
  Banker = 6,
  PetitionVendor = 7,
  GuildTabardVendor = 8,
  Battlemaster = 9,
  Auctioneer = 10,
  TalentMaster = 11,
  Stablemaster = 12,
  PetSpecializationMaster = 13,
  GuildBanker = 14,
  Spellclick = 15,
  DisableXPGain = 16,
  EnableXPGain = 17,
  Mailbox = 18,
  WorldPvPQueue = 19,
  LFGDungeon = 20,
  ArtifactRespec = 21,
  CemeterySelect = 22,
  SpecializationMaster = 23,
  GlyphMaster = 24,
  QueueScenario = 25,
  GarrisonArchitect = 26,
  GarrisonMissionNpc = 27,
  ShipmentCrafter = 28,
  GarrisonTradeskillNpc = 29,
  GarrisonRecruitment = 30,
  AdventureMap = 31,
  GarrisonTalent = 32,
  ContributionCollector = 33,
  Transmogrify = 34,
  AzeriteRespec = 35,
  IslandsMissionNpc = 36,
  UIItemInteraction = 37,
  WorldMap = 38,
  Soulbind = 39,
  ChromieTimeNpc = 40,
  CovenantPreviewNpc = 41,
  RuneforgeLegendaryCrafting = 42,
  NewPlayerGuide = 43,
  RuneforgeLegendaryUpgrade = 44,
  CovenantRenownNpc = 45,
  BlackMarketAuctionHouse = 46,
  PerksProgramVendor = 47,
  ProfessionsCraftingOrder = 48,
  ProfessionsOpen = 49,
  ProfessionsCustomerOrder = 50,
  TraitSystem = 51,
  BarbersChoice = 52,
  MajorFactionRenown = 53,
  PersonalTabardVendor = 54,
  ForgeMaster = 55,
  CharacterBanker = 56,
  AccountBanker = 57,
  ProfessionRespec = 58,
  Placeholder_1 = 59,
  Placeholder_2 = 60,
  Placeholder_3 = 61,
  GuildRename = 62,
  Placeholder_4 = 63,
  ItemUpgrade = 64,
}

export const GossipNpcOptionSchema = Schema.Enums(GossipNpcOption);
