//! Resource type definitions.

use serde::Deserialize;

/// Class resource types.
///
/// Resources fall into categories:
/// - **Regenerating**: Focus, Energy, Mana, Essence (regen over time, haste-scaled)
/// - **Builder/Spender**: Rage, Runic Power, Fury, Pain, Maelstrom, Insanity, Astral Power
/// - **Combo-style**: Combo Points, Chi, Holy Power (build to max, spend for finishers)
/// - **Special**: Soul Shards (fragments), Arcane Charges, Runes (separate system)
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "snake_case")]
#[repr(u8)]
pub enum ResourceType {
    // === Regenerating (haste-scaled) ===
    #[default]
    Mana = 0,
    Focus = 1,
    Energy = 2,
    Essence = 3,

    // === Builder/Spender (no passive regen) ===
    Rage = 10,
    RunicPower = 11,
    Fury = 12,
    Pain = 13,
    Maelstrom = 14,
    Insanity = 15,
    AstralPower = 16,

    // === Combo-style (integer-based) ===
    ComboPoints = 20,
    Chi = 21,
    HolyPower = 22,
    ArcaneCharges = 23,

    // === Special ===
    SoulShards = 30,
    // Runes are handled separately via RuneSet
}

impl ResourceType {
    /// Returns true if this resource regenerates passively over time.
    /// These resources also scale with haste.
    #[inline]
    pub const fn is_regenerating(&self) -> bool {
        matches!(
            self,
            ResourceType::Mana
                | ResourceType::Focus
                | ResourceType::Energy
                | ResourceType::Essence
        )
    }

    /// Returns true if this resource type uses integer values (combo points, etc.).
    #[inline]
    pub const fn is_integer(&self) -> bool {
        matches!(
            self,
            ResourceType::ComboPoints
                | ResourceType::Chi
                | ResourceType::HolyPower
                | ResourceType::ArcaneCharges
                | ResourceType::SoulShards
        )
    }

    /// Returns true if this is a builder/spender resource (generated by attacks).
    #[inline]
    pub const fn is_builder_spender(&self) -> bool {
        matches!(
            self,
            ResourceType::Rage
                | ResourceType::RunicPower
                | ResourceType::Fury
                | ResourceType::Pain
                | ResourceType::Maelstrom
                | ResourceType::Insanity
                | ResourceType::AstralPower
        )
    }

    /// Display name for the resource type.
    #[inline]
    pub const fn name(&self) -> &'static str {
        match self {
            ResourceType::Mana => "Mana",
            ResourceType::Focus => "Focus",
            ResourceType::Energy => "Energy",
            ResourceType::Essence => "Essence",
            ResourceType::Rage => "Rage",
            ResourceType::RunicPower => "Runic Power",
            ResourceType::Fury => "Fury",
            ResourceType::Pain => "Pain",
            ResourceType::Maelstrom => "Maelstrom",
            ResourceType::Insanity => "Insanity",
            ResourceType::AstralPower => "Astral Power",
            ResourceType::ComboPoints => "Combo Points",
            ResourceType::Chi => "Chi",
            ResourceType::HolyPower => "Holy Power",
            ResourceType::ArcaneCharges => "Arcane Charges",
            ResourceType::SoulShards => "Soul Shards",
        }
    }
}

impl std::fmt::Display for ResourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_regenerating_resources() {
        assert!(ResourceType::Focus.is_regenerating());
        assert!(ResourceType::Energy.is_regenerating());
        assert!(ResourceType::Mana.is_regenerating());
        assert!(ResourceType::Essence.is_regenerating());

        assert!(!ResourceType::Rage.is_regenerating());
        assert!(!ResourceType::ComboPoints.is_regenerating());
    }

    #[test]
    fn test_integer_resources() {
        assert!(ResourceType::ComboPoints.is_integer());
        assert!(ResourceType::Chi.is_integer());
        assert!(ResourceType::HolyPower.is_integer());

        assert!(!ResourceType::Focus.is_integer());
        assert!(!ResourceType::Rage.is_integer());
    }

    #[test]
    fn test_builder_spender() {
        assert!(ResourceType::Rage.is_builder_spender());
        assert!(ResourceType::RunicPower.is_builder_spender());
        assert!(ResourceType::Fury.is_builder_spender());

        assert!(!ResourceType::Focus.is_builder_spender());
        assert!(!ResourceType::ComboPoints.is_builder_spender());
    }
}
